// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package DAL

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
}
